# Generated by Django 3.2.4 on 2021-06-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_skill_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='question',
        ),
        migrations.AddField(
            model_name='skill',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Level'),
        ),
    ]
