# Generated by Django 3.2.4 on 2021-06-15 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210614_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AlterField(
            model_name='skill',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.skill_cat'),
        ),
        migrations.AlterField(
            model_name='skill_cat',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skill_cat',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.skill_level'),
        ),
    ]
