# Generated by Django 3.2.4 on 2021-06-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210615_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_cat',
            name='score1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill_cat',
            name='score2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill_cat',
            name='score3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='skill_cat',
            name='score4',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Score_Agg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_agg', models.FloatField(null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.skill_level')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.people')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.skill_cat')),
            ],
        ),
    ]
