# Generated by Django 3.2.4 on 2021-06-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210619_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('primary_dark', models.CharField(max_length=10)),
                ('primary_light', models.CharField(max_length=10)),
                ('secondary_dark', models.CharField(max_length=10)),
                ('secondary_light', models.CharField(max_length=10)),
            ],
        ),
    ]
