# Generated by Django 3.2.4 on 2021-06-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='colour',
            name='nav',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colour',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='colour',
            name='primary_dark',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colour',
            name='primary_light',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colour',
            name='secondary_dark',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colour',
            name='secondary_light',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
