# Generated by Django 3.2 on 2021-06-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_roles_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Role_Level',
        ),
        migrations.AddField(
            model_name='people',
            name='role_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role_level'),
        ),
    ]
