# Generated by Django 3.2 on 2021-06-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_skill_cat_to_develop'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_cat',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
