# Generated by Django 3.2 on 2021-06-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_skill_cat_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='score_temp',
            field=models.IntegerField(null=True),
        ),
    ]
