# Generated by Django 4.0 on 2021-12-26 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210624_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Person', 'Person'), ('Objective', 'Objective'), ('Story', 'Story'), ('Issue', 'Issue'), ('To Do', 'To Do'), ('Group', 'Group'), ('Reminder', 'Reminder')], max_length=64, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_rn', to='app.note')),
            ],
        ),
    ]
