# Generated by Django 4.0 on 2021-12-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_note_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
