# Generated by Django 4.0 on 2021-12-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_note_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='time_stamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
