# Generated by Django 4.0 on 2021-12-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_note_created_by_note_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
