# Generated by Django 4.0 on 2022-01-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.TextField(blank=True, choices=[('Not asked', 'Not asked'), ('Requested and Open', 'Requested and Open'), ('Complete', 'Complete')], default='Not asked', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('Group', 'Group'), ('Person', 'Person'), ('Objective', 'Objective'), ('Story', 'Story'), ('Issue', 'Issue'), ('ToDo', 'ToDo'), ('Report', 'Report'), ('Reminder', 'Reminder'), ('Meeting', 'Meeting'), ('Holiday', 'Holiday'), ('Medical', 'Medical'), ('Grateful', 'Grateful'), ('Life', 'Life')], max_length=64, null=True),
        ),
    ]
