# Generated by Django 4.0 on 2022-01-22 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_mindmap_node_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='app.mindmap'),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='size_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='size_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
