# Generated by Django 4.0 on 2022-01-22 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_node_map_alter_mindmap_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mindmap'),
        ),
        migrations.AlterField(
            model_name='node',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.mindmap'),
        ),
    ]
