# Generated by Django 4.0 on 2022-01-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_node_fontcolour'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mindmap'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='node_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='app.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='node_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='app.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='colour',
            field=models.CharField(choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('orange', 'orange'), ('black', 'black'), ('white', 'white')], default='blue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='shape',
            field=models.CharField(choices=[('rect', 'rect')], default='rect', max_length=255, null=True),
        ),
    ]
