# Generated by Django 4.0 on 2022-02-08 06:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_note_fancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
